
[[redirects]]
from = "/api/*"
to = "/netlify/functions/:splat"
status = 200

# Header rules for the API endpoint
[[headers]]
# Apply these headers to all routes under /api/
for = "/api/*"
[headers.values]
# Allow requests from any origin
Access-Control-Allow-Origin = "*"
# Specify allowed HTTP methods
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
# Specify allowed request headers
Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
